version: '3.8'

services:
  proxy-server:
    container_name: proxy-server
    image: nginx:1.19
    ports:
      - "80:80"
      - "433:443"
    depends_on:
      - api-service
    volumes:
      - ./nginx/proxy-server.conf:/etc/nginx/nginx.conf

  api-service:
    container_name: api-service
    image: nginx:1.19
    expose:
      - "8181"
    depends_on:
      - api-php-fpm
    volumes:
      - ./source/web:/source
      - ./nginx/api-service.conf:/etc/nginx/nginx.conf

  api-php-fpm:
    container_name: api-php-fpm
    build: 
      context: ./api-php-fpm/
      dockerfile: Dockerfile
    expose:
      - "9000"
    volumes:
      - ./source/web:/source
      - ./api-php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini