version: '3.8'

services:
  proxy-server:
    container_name: proxy-server
    image: nginx:1.19
    ports:
      - "80:80"
      - "433:443"
    depends_on:
      - api-server
    volumes:
      - ./nginx/proxy-server.conf:/etc/nginx/nginx.conf

  api-server:
    container_name: api-server
    image: nginx:1.19
    expose:
      - "8181"
    depends_on:
      - php7-fpm
    volumes:
      - ./source/web:/source
      - ./nginx/api-server.conf:/etc/nginx/nginx.conf

  php7-fpm:
    container_name: php7-fpm
    build: 
      context: ./php7-fpm/
      dockerfile: Dockerfile
    expose:
      - "9000"
    volumes:
      - ./source/web:/source
      - ./php7-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini