version: '3.8'

services:
  apache:
    container_name: apache
    build:
      context: ./apache/
      dockerfile: Dockerfile
    ports:
       - 80:80
       - 443:443
    volumes: 
      - /mnt/d/02.Workspace/wsl.docker/source/web:/htdocs

  php:
    container_name: php
    build: 
      context: ./php7/
      dockerfile: Dockerfile
    expose:
      - "9000"
    volumes:
      - ./php7/php.ini:/usr/local/etc/php/conf.d/php.ini